### ISSUE TITLE
Travis pipelines are broken due to long output

### ISSUE THREAD

**Issue by pplu** [pplu/aws-sdk-perl#362]
Looks like travis pipelines are failing due to the long output of Paws testing
https://travis-ci.org/pplu/aws-sdk-perl/builds/621351059

**Comment by torrentalle** [comment]
This pipeline uses the [Perl Module Travis-CI Helper](https://github.com/travis-perl/helpers) in `auto `mode. I don't know why, when this mode is used, the pipeline tries to build the package twice, [first using Dist::Zilla](https://travis-ci.org/pplu/aws-sdk-perl/jobs/621351060#L329)

```
[ ... ]
$ build-dist
Building with Dist::Zilla
[ ... ]
```

[and later, using standard Perl commands](https://travis-ci.org/pplu/aws-sdk-perl/jobs/621351060#L346) the pipeline tries to build the package another time.

```
[ ... ]
$ cd /home/travis/build/pplu/aws-sdk-perl/build_dir
$ cpanm --quiet --installdeps --notest .
$ perl Build.PL && ./Build && ./Build test
Creating new 'Build' script for 'Paws' version '0.42'
cp lib/Paws/MediaPackageVod/PackagingConfigurationCreateParameters.pm blib/lib/Paws/MediaPackageVod/PackagingConfigurationCreateParameters.pm
[ ... ]
```
This second build is trigered by the default `install` provided by standard [Travis-CI Perl integration](https://docs.travis-ci.com/user/languages/perl/), but is executed into `./build_dir`, regenetating Build.PL scripts and moving all `lib` files to `blib` folder . **This is causing the job exceeded the maximum log length error**

To solve this build issue, I modified `.travis.yml` configuration file to execute the Perl Build Helper manually, as following [helper documentation](https://github.com/travis-perl/helpers#example-long-travisyml), removing unused features like coverage

```yml
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
```

MR #374 provides a fix for this issue. https://travis-ci.com/torrentalle/aws-sdk-perl
